name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/apidev:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.14.8

    - name: Initialize Terraform
      run: terraform init
      working-directory: terraform/environments/dev

    - name: Create SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
    
    - name: Apply Terraform configuration
      run: terraform apply -auto-approve
      working-directory: terraform/environments/dev
      env:
        TF_VAR_environment: dev

    - name: Get Terraform Output
      id: tfout
      run: |
        echo "EC2_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV
      working-directory: terraform/environments/dev

    - name: Create Ansible inventory
      run: |
        mkdir -p ansible/inventory

        cat <<EOF > ansible/inventory/hosts.ini
        [web]
        $EC2_IP ansible_user=ec2-user ansible_ssh_private_key_file=key.pem
        EOF

    - name: Create vault password file
      run: |
        echo "${{ secrets.ANSIBLE_VAULT_PASS }}" > vault.pass

    - name: Run ansible playbook
      run: |
        ansible-playbook \
        -i ansible/inventory/hosts.ini ansible/playbooks/deploy.yml \
        --vault-password-file vault.pass

